---
name: "Avlist"
guid: "6730eca4-1058-4f28-aace-cb60965ad500"
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "AvList metadata provider"
description: >
  AvList metadata provider
category: "Metadata"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.AvList.dll"
changelog: >
  changelog
